### ISSUE TITLE
Stackblitz

### ISSUE THREAD

**Issue by JonasReichhardt** [rstropek-teaching/turmrechnen-quiz-4ahif-JonasReichhardt#1]
Started working on the exercise

https://stackblitz.com/edit/turmrechnen

**Comment by rstropek** [comment]
Thank you for the link. Please let me know when you are done so that I can check the result and code.

Greetings,
Rainer Stropek.

**Comment by JonasReichhardt** [comment]
@rstropek 

I finished the exercise and you can test it [here](https://turmrechnen.stackblitz.io/)

**Comment by rstropek** [comment]
Nearly. The error message *Height must be >=2* must appear whenever height contains an invalid value. Displaying it after clicking *calculate* is too late.

Greetings,
Rainer Stropek

**Comment by JonasReichhardt** [comment]
Ok I misread that part. I'm going to fix it and will notify you

Greetings,
Jonas Reichhardt

**Comment by JonasReichhardt** [comment]
Exercies is completly finished and available at stackblitz.

**Comment by rstropek** [comment]
Well done, your extra point is secured.

Greetings,
Rainer Stropek.
