### ISSUE TITLE
Nested ngFor

### ISSUE THREAD

**Issue by JonasReichhardt** [rstropek-teaching/turmrechnen-quiz-4ahif-JonasReichhardt#2]
Dear @rstropek 

In my exercise I'm saving my tower into a 2 dimensional array with the format:

[[5,2,10]
[10,3,30]
.....]

now I want to loop trough the array using *ngFor. I've tried some databinding as you can see on stackblitz with {{ line[0] }} to get the first element of the current one dimensional array but it is not working.

How am I supposed to use a nested ngFor to get my array onto the .html page?

**Comment by rstropek** [comment]
Hi @JonasReichhardt 

I think you have a different problem ;-) Your code uses an uninitialized variable `i` in the `for` loop in line 22. Try initializing it with zero, that should help finishing the example.

Greetings,
Rainer Stropek.

**Comment by JonasReichhardt** [comment]
@rstropek Thank you for your quick response.
